# Generated by Django 4.1.2 on 2022-10-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('salary', models.IntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
