# Generated by Django 4.1.2 on 2022-10-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location_jobpost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('FT', 'FULL TIME'), ('PT', 'PART TIME'), ('I', 'INTERNSHIP')], default='FT', max_length=200),
        ),
    ]
