# Generated by Django 4.1.2 on 2022-10-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobpost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Internship', 'Internship')], default='Full time', max_length=10),
        ),
    ]
